Agent: fix exception from TNonblockingServer
In promote (inf3/vsan), agent failed to become available due to
the following exception from TNonblockingServer. It causes agent
to quit and restart.

In common/log.py, we overwrite the logging implementation to
improve multi-line logs. Although our logging implementation
works in most cases, it cannot handle complex params like
sys.exc_info().

logger.exception is a better way to log exceptions, and works
with our implementation.

Exception:
==========
agent/agent.py", line 209, in start_wrapper
agent/agent.py", line 82, in start
agent/agent.py", line 155, in _start_thrift_service
thrift/server/TNonblockingServer.py", line 352, in serve
thrift/server/TNonblockingServer.py", line 319, in handle
/lib/python2.7/logging/__init__.py", line 1155, in debug
common/log.py", line 239, in _log
TypeError: not all arguments converted during string formatting

Change-Id: I3803bd00ab83068d9adec486aa709e5c90439c89