"system destroy" in ruby cli should correctly list hosts
Under system.rb we should find size  on hostList.items, instead of hostList.
It currently gives error undefined method `size' for #<EsxCloud::HostList> NoMethodError

Change-Id: I2a07f1b749d86b5d5bd97c61f691ac283d802102